# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
# cache: packages

env:
  global:
  - MAKEFLAGS="-j 2"

bioc_packages: Biobase

r_packages: 
  - NMF
  - RANN
  - fastICA
  - RcppRoll
  - Matrix
  - ipred
  - RSpectra


r:
- 3.1
- 3.2
- oldrel
- release
- devel

matrix:
  allow_failures:
    - r: 3.1

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
